sudo: false

language: php

# Run on PHP 7.2 and newer
php:
  - 7.2
  - nightly

# Cache yarn
cache:
  yarn: true
  directories:
    - $HOME/.composer
    - vendor/

before_install:
  # Install NodeJS
  - nvm install node
  - npm install -g yarn

install:
  # Move to Gumbo Millennium plugin
  - cd "$( git rev-parse --show-toplevel 2>/dev/null)/gumbo-millennium"

  # Download composer assets
  - composer install --no-progress --no-suggest -an

  # Download Yarn assets using lockfile
  - yarn install --frozen-lockfile

script:
  # Move to Gumbo Millennium plugin
  - cd "$( git rev-parse --show-toplevel 2>/dev/null)/gumbo-millennium"

  # Lint PHP code
  - vendor/bin/phpcs

  # Lint Sass files
  - find lib/sass -type f -name '*.scss' -print | xargs node_modules/.bin/stylelint

  # Lint Javascript
  - find lib/ -type f -name '*.js' -print | xargs node_modules/.bin/eslint
  - find lib/ -type f -name '*.jsx' -print | xargs node_modules/.bin/eslint

  # Make zipfile
  - make gumbo-millennium.zip

  # Copy zipfile to git root
  - cp "gumbo-millennium.zip" "$( git rev-parse --show-toplevel 2>/dev/null)/gumbo-millennium.zip"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

deploy:
  provider: releases
  api_key:
    secure: IxPjPcVah6JWvfjbQfm+gLYCQhduxOeBXeumQ+26LRd2RH+UowMRrXNYMU21cHErXqn8DbRGzd3vti7xI0z3S1Nn+FFkvOPFU31ycsYXmfgoMrUG4eTfebYfw7aBjyrenSQ4ojkEqGA8San8MYykA6O/MFpHTnNQEkHaeV9WpEp2E9qqn3gxICt0tvwc9SgJcf7KRG6i/zzur990QKZfs+l2vQXD68V0iuS89TRrERNnXaEpN02h877sVlD/b87/Zr+4kfWPeoVc123E34XhJvDHZOGh6KfNmySO55pbkIUu3lsCN+ojWRpC5B+pj3Xyrmz/HzO9MiriLMpijChYihLk5KxkbTlXrc/mVNYE2+YovJhXralGG7PuVCGsAdIPuBQXQLVDDgqgy0KO7UtZAmzFktJRRPRAb3vIZpF9KTHHKaGQXKVEDom52X5fq3D1ndElTeIo+s0V3VqQeshzri8KWT588uTjPjHFqzqHeewvI7DlSqD1+qPjD5Dmes855mZGwncuBSKUyEDnIUZBqbQv1y+anAxT5XPP+E3yvnCI7jDeYGiHjX0vOJIoepitYY1d0r8o5pMkYTImn+PZVISs1p+U3wBfrHtNRxLIPtm0faSCGofmkOcwZPinzTySezEW8LqS8WtGDQkDcfsbEntygJuh2sL3/+++FKUzTHo=
  file: "gumbo-millennium.zip"
  skip_cleanup: true
  on:
    tags: true
